import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { createApp } from '../server/index.js';
import { FileStore } from '../server/store.js';
import { createStorageNode } from '../server/storage-node.js';
import { backupSQLite, copyStore, migrateStore, resetPassword } from '../tools/admin.js';
import { fixture } from './helpers/fixture.js';
test('One file-store writer per directory is enforced; stale crashed-process locks are recovered',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'orivane-lock-'));let a;try{a=await new FileStore(dir).init();await assert.rejects(()=>new FileStore(dir).init(),/already has a writer/);await a.close();a=null;await writeFile(path.join(dir,'.writer.lock'),JSON.stringify({pid:2147483647,host:os.hostname(),token:'stale'}));a=await new FileStore(dir).init();await a.put('x',{n:1});assert.equal((await a.get('x')).n,1);}finally{await a?.close();await rm(dir,{recursive:true,force:true});}});
test('Offline file backup and migration preserve account/document keys without overwriting targets',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'orivane-copy-')),src=path.join(dir,'source'),dest=path.join(dir,'backup'),key='cluster-secret-at-least-32-characters';let app;try{const store=await new FileStore(src).init();await store.put('identity',{users:{user:{name:'User'}}});await store.put('room:123456789012345678901234',{id:'123456789012345678901234',snapshot:{test:true}});await assert.rejects(()=>copyStore(src,dest),/writer/);await store.close();assert.equal((await copyStore(src,dest)).keys,2);const backup=await new FileStore(dest).init();assert.equal((await backup.get('identity')).users.user.name,'User');await backup.close();app=await createStorageNode({filename:path.join(dir,'cluster.sqlite'),secret:key});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+app.server.address().port;assert.equal((await migrateStore(src,url,key)).migratedKeys,2);await assert.rejects(()=>migrateStore(src,url,key),/matching keys/);}finally{await app?.close();await rm(dir,{recursive:true,force:true});}});
test('Live SQLite backup is a consistent, integrity-checked snapshot of committed WAL state',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'orivane-backup-')),src=path.join(dir,'live.sqlite'),dest=path.join(dir,'backup.sqlite');const db=new DatabaseSync(src);try{db.exec('PRAGMA journal_mode=WAL; CREATE TABLE test(n INTEGER); INSERT INTO test VALUES(42)');assert.equal((await backupSQLite(src,dest)).integrity,'ok');const restored=new DatabaseSync(dest);assert.equal(restored.prepare('SELECT n FROM test').get().n,42);restored.close();db.exec('INSERT INTO test VALUES(99)');await assert.rejects(()=>backupSQLite(src,dest),/overwrite/);}finally{db.close();await rm(dir,{recursive:true,force:true});}});
test('Host-administrator password recovery revokes prior sessions and uses a new scrypt hash',async()=>{const f=await fixture();try{const auth=await f.register();await resetPassword(f.app.store,'owner@example.test','Recovered-password-is-long-123!');const prior=await(await f.request('/api/auth/me',undefined,auth)).json();assert.equal(prior.user,null);assert.equal((await f.request('/api/auth/login',{email:'owner@example.test',password:'Recovered-password-is-long-123!'})).status,200);}finally{await f.close();}});

test('Concurrent initializers never acquire the same local store, including stale-lock recovery',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'orivane-concurrent-lock-'));let winner;try{await writeFile(path.join(dir,'.writer.lock'),JSON.stringify({pid:2147483647,host:os.hostname(),token:'stale'}));const results=await Promise.allSettled(Array.from({length:12},()=>new FileStore(dir).init()));const wins=results.filter(r=>r.status==='fulfilled');assert.equal(wins.length,1);winner=wins[0].value;await winner.put('one',{safe:true});}finally{await winner?.close();await rm(dir,{recursive:true,force:true});}});
test('Failed app configuration releases its local storage writer lock',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'orivane-init-fail-'));try{await assert.rejects(()=>createApp({dataDir:dir,identity:{publicOrigin:'http://public-insecure.example'}}));const store=await new FileStore(dir).init();await store.close();}finally{await rm(dir,{recursive:true,force:true});}});
test('Failed remote migration initialization releases its source writer lock',async()=>{const dir=await mkdtemp(path.join(os.tmpdir(),'orivane-migrate-fail-'));try{await assert.rejects(()=>migrateStore(dir,'http://127.0.0.1:1','cluster-secret-at-least-32-characters'));const store=await new FileStore(dir).init();await store.close();}finally{await rm(dir,{recursive:true,force:true});}});
