import test from 'node:test';
import assert from 'node:assert/strict';
import { fork } from 'node:child_process';
import { mkdtemp, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { RemoteStore } from '../server/store.js';
import { BoardDocument } from '../public/core/model.js';
import { Collaboration } from '../public/core/collaboration.js';
import { wait } from './helpers/fixture.js';
const secret='cluster-secret-with-at-least-32-characters';
class Memory {constructor(){this.map=new Map();}async get(t,id){return structuredClone(this.map.get(t+id));}async put(t,v){this.map.set(t+v.id,structuredClone(v));}}
async function worker(kind, options) {const child=fork(new URL('./helpers/worker.js',import.meta.url),[],{env:{...process.env,ORIVANE_WORKER_KIND:kind,ORIVANE_WORKER_OPTIONS:JSON.stringify(options)},stdio:['ignore','pipe','pipe','ipc']});let log='';child.stdout.on('data',c=>log+=c);child.stderr.on('data',c=>log+=c);const port=await new Promise((resolve,reject)=>{child.once('message',m=>resolve(m.port));child.once('error',reject);child.once('exit',code=>reject(Error('Worker exited '+code+': '+log)));});return {child,port,base:'http://127.0.0.1:'+port,async stop(crash=false){if(child.exitCode!==null||child.signalCode!==null)return;const exited=new Promise(r=>child.once('exit',r));if(crash)child.kill('SIGKILL');else child.send('stop');await exited;},get log(){return log;}};}
test('Real SQLite storage node provides atomic CAS under concurrent network clients and survives a process crash',async()=>{const directory=await mkdtemp(path.join(os.tmpdir(),'orivane-cluster-'));let storage;try{storage=await worker('storage',{filename:path.join(directory,'shared.sqlite'),secret});const a=await new RemoteStore(storage.base,secret).init(),b=await new RemoteStore(storage.base,secret).init();await Promise.all(Array.from({length:48},(_,i)=>(i%2?a:b).transaction('counter',value=>({value:{count:(value?.count||0)+1}}))));assert.equal((await a.get('counter')).count,48);const port=storage.port;await storage.stop(true);storage=await worker('storage',{filename:path.join(directory,'shared.sqlite'),secret,port});assert.equal((await a.get('counter')).count,48);assert.equal((await fetch(storage.base+'/state/counter',{headers:{Authorization:'Bearer wrong'}})).status,403);assert.equal((await fetch(storage.base+'/state/counter',{headers:{Authorization:'Bearer '+secret,Origin:'https://evil.test'}})).status,403);}finally{await storage?.stop();await rm(directory,{recursive:true,force:true});}});
test('Two independent API processes synchronize text, presence, identity and revocation without sticky sessions',async()=>{const directory=await mkdtemp(path.join(os.tmpdir(),'orivane-replicas-'));let storage,a,b;const clients=[];try{storage=await worker('storage',{filename:path.join(directory,'shared.sqlite'),secret});const config={storageURL:storage.base,clusterSecret:secret,dataDir:directory,pollInterval:75};a=await worker('api',config);b=await worker('api',config);
const seed=new BoardDocument('seed');seed.transact([{id:'n',props:{type:'sticky',text:'Hello world',x:0,y:0,w:160,h:160}}]);const room=await(await fetch(a.base+'/api/rooms',{method:'POST',body:JSON.stringify({snapshot:seed.snapshot()})})).json();
async function client(base,actor){globalThis.location={protocol:'http:',origin:base};const c=new Collaboration(new BoardDocument(actor),new Memory(),'room:'+room.id,{name:actor,color:'#7656d9'});c.base=base;clients.push(c);await c.connect(room.id,room.editorToken);await wait(()=>c.connected);return c;}
const ca=await client(a.base,'alpha'),cb=await client(b.base,'beta');ca.doc.transact([{id:'n',props:{text:'Hello A world'}}]);cb.doc.transact([{id:'n',props:{text:'Hello B world'}}]);await wait(()=>ca.doc.get('n').text.includes('A')&&ca.doc.get('n').text.includes('B')&&ca.doc.canonical()===cb.doc.canonical(),'cross-process CRDT');await wait(()=>!ca.pending.length&&!cb.pending.length);
ca.presence({cursor:{x:145,y:87}});await wait(()=>cb.peers.get('alpha')?.cursor?.x===145,'cross-process presence');
const reg=await fetch(a.base+'/api/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:'Shared Identity',email:'shared@example.test',password:'a-password-over-12'})}),cookie=reg.headers.get('set-cookie').split(';')[0];const me=await(await fetch(b.base+'/api/auth/me',{headers:{Cookie:cookie}})).json();assert.equal(me.user.name,'Shared Identity');
const snapshot=ca.doc.canonical();ca.destroy();await a.stop(true);a=await worker('api',config);const cc=await client(a.base,'gamma');assert.equal(cc.doc.canonical(),snapshot);
const headers={Authorization:'Bearer '+room.ownerToken,'X-Orivane-Actor':'owner','X-Orivane-Client':'ownerclient__________________','Content-Type':'application/json'};const rotated=await fetch(a.base+'/api/rooms/'+room.id+'/invites',{method:'POST',headers,body:'{}'});assert.equal(rotated.status,200);await wait(()=>!cb.connected,'revocation reaches other worker');const revoked=await fetch(b.base+'/api/rooms/'+room.id+'/snapshot',{headers:{Authorization:'Bearer '+room.editorToken,'X-Orivane-Actor':'viewer'}});assert.equal(revoked.status,403);
}catch(e){console.error(a?.log,b?.log,storage?.log);throw e;}finally{for(const c of clients)c.destroy();await a?.stop();await b?.stop();await storage?.stop();await rm(directory,{recursive:true,force:true});}});
test('Storage outage does not acknowledge or partially broadcast an edit; retry after recovery is durable',async()=>{const directory=await mkdtemp(path.join(os.tmpdir(),'orivane-outage-'));let storage,api;try{storage=await worker('storage',{filename:path.join(directory,'shared.sqlite'),secret});api=await worker('api',{storageURL:storage.base,clusterSecret:secret,dataDir:directory});const seed=new BoardDocument('seed');seed.transact([{id:'n',props:{type:'text',text:'before'}}]);const room=await(await fetch(api.base+'/api/rooms',{method:'POST',body:JSON.stringify({snapshot:seed.snapshot()})})).json();const h={Authorization:'Bearer '+room.editorToken,'X-Orivane-Actor':'a','X-Orivane-Client':'persistentclient_____________','Content-Type':'application/json'},op={id:'outage-edit',actor:'a',clock:2,changes:[{id:'n',props:{x:44}}]};const port=storage.port;await storage.stop(true);const failed=await fetch(api.base+'/api/rooms/'+room.id+'/ops',{method:'POST',headers:h,body:JSON.stringify(op)});assert.equal(failed.status,503);storage=await worker('storage',{filename:path.join(directory,'shared.sqlite'),secret,port});const retry=await fetch(api.base+'/api/rooms/'+room.id+'/ops',{method:'POST',headers:h,body:JSON.stringify(op)});assert.equal(retry.status,200);const d=new BoardDocument('verify');d.merge(await(await fetch(api.base+'/api/rooms/'+room.id+'/snapshot',{headers:h})).json());assert.equal(d.get('n').x,44);}finally{await api?.stop();await storage?.stop();await rm(directory,{recursive:true,force:true});}});
