import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import { createHmac } from 'node:crypto';
import { fixture } from './helpers/fixture.js';
import { ProviderService } from '../server/providers.js';
import { privateAddress, requestExternal } from '../server/network.js';
async function mock(handler){const requests=[];const server=http.createServer(async(req,res)=>{let text='';for await(const chunk of req)text+=chunk;requests.push({url:req.url,method:req.method,headers:req.headers,text});await handler(req,res,text);});await new Promise(r=>server.listen(0,'127.0.0.1',r));return{base:'http://127.0.0.1:'+server.address().port,requests,close:()=>new Promise(r=>server.close(r))};}
test('OpenAI-compatible and Ollama adapters call real HTTP fixtures, constrain output and require consent',async()=>{const remote=await mock((req,res,text)=>{const b=JSON.parse(text);assert.equal(b.messages[0].role,'system');res.setHeader('Content-Type','application/json');const content=JSON.stringify({summary:'A useful summary',nodes:[{type:'sticky',text:'Idea'},{type:'script',text:'Safe plain text'}],edges:[{from:0,to:1,label:'connect'},{from:99,to:0,label:'invalid'}]});res.end(JSON.stringify(req.url==='/api/chat'?{message:{content}}:{choices:[{message:{content}}],usage:{total_tokens:55}}));});const f=await fixture();try{for(const kind of ['openai-compatible','ollama']){const p=new ProviderService(f.app.store,{ai:{kind,base:remote.base,model:'fixture-model',key:'fixture-key',allowPrivate:true}});await assert.rejects(()=>p.ai({task:'summarize',items:[],consent:false}),/consent/);const result=await p.ai({task:'diagram',items:[{id:'x',text:'Selected text'}],consent:true});assert.equal(result.nodes[1].type,'sticky');assert.equal(result.edges.length,1);assert.equal(result.requiresReview,true);}assert.equal(remote.requests.length,2);assert.equal(remote.requests[0].headers.authorization,'Bearer fixture-key');}finally{await f.close();await remote.close();}});
test('Provider JSON is never code-executed and invalid output leaves the board untouched',async()=>{const remote=await mock((req,res)=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify({choices:[{message:{content:'<script>destroyEverything()</script>'}}]}));});const f=await fixture();try{const p=new ProviderService(f.app.store,{ai:{kind:'openai-compatible',base:remote.base,model:'fixture',allowPrivate:true}});await assert.rejects(()=>p.ai({task:'summarize',items:[],consent:true}),/valid JSON/);}finally{await f.close();await remote.close();}});
test('GitHub import/create/update enforces repository allowlists and external-write idempotency',async()=>{let writes=0;const remote=await mock((req,res,text)=>{res.setHeader('Content-Type','application/json');if(req.method==='GET')res.end(JSON.stringify([{number:1,title:'Imported issue',state:'open',html_url:'https://github.com/team/repo/issues/1',assignee:{login:'owner'}},{number:2,title:'PR',pull_request:{}}]));else{writes++;res.end(JSON.stringify({number:3,title:JSON.parse(text).title,state:'open',html_url:'https://github.com/team/repo/issues/3'}));}});const f=await fixture();try{const p=new ProviderService(f.app.store,{github:{base:remote.base,token:'credential',repositories:['team/repo'],allowPrivate:true}});await assert.rejects(()=>p.integration('github','import',{repository:'other/repo'}),/allowlist/);const read=await p.integration('github','import',{repository:'team/repo'});assert.equal(read.items.length,1);const input={repository:'team/repo',title:'Created',confirm:true};const run=()=>p.once('user','unique_request_0123456789',input,()=>p.integration('github','create',input));const a=await run(),b=await run();assert.deepEqual(a,b);assert.equal(writes,1);await assert.rejects(()=>p.once('user','unique_request_0123456789',{different:true},()=>{}),/another request/);await p.integration('github','update',{...input,number:3});assert.equal(writes,2);assert.equal(remote.requests.at(-1).method,'PATCH');}finally{await f.close();await remote.close();}});
test('Jira search and issue writes use enhanced search API and structured document descriptions',async()=>{const remote=await mock((req,res,text)=>{const input=JSON.parse(text);res.setHeader('Content-Type','application/json');if(req.url.endsWith('/search/jql')){assert.match(input.jql,/project = "TEAM"/);res.end(JSON.stringify({issues:[{key:'TEAM-1',fields:{summary:'Issue',status:{name:'Open'},assignee:{displayName:'User'}}}]}));}else{assert.equal(input.fields.description.type,'doc');res.end(JSON.stringify({key:'TEAM-2'}));}});const f=await fixture();try{const p=new ProviderService(f.app.store,{jira:{base:remote.base,email:'admin@example.test',token:'token',projects:['TEAM'],allowPrivate:true}});assert.equal((await p.integration('jira','import',{project:'TEAM'})).items[0].external,'jira:TEAM-1');assert.equal((await p.integration('jira','create',{project:'TEAM',title:'Title',description:'Description',confirm:true})).external,'jira:TEAM-2');await assert.rejects(()=>p.integration('jira','update',{project:'TEAM',issue:'OTHER-1',title:'No',confirm:true}),/selected project/);}finally{await f.close();await remote.close();}});
test('Slack confirms delivery and durable outgoing webhooks have timestamped HMAC signatures',async()=>{let hookBody,hookHeaders;const remote=await mock((req,res,text)=>{if(req.url==='/slack'){res.end('ok');}else{hookBody=text;hookHeaders=req.headers;res.writeHead(204);res.end();}});const f=await fixture();try{const p=new ProviderService(f.app.store,{slack:{webhook:remote.base+'/slack',allowPrivate:true},webhook:{url:remote.base+'/hook',secret:'a-signing-secret-at-least-32-characters',allowPrivate:true}});await assert.rejects(()=>p.integration('slack','post',{text:'hello'}),/Confirm/);assert.equal((await p.integration('slack','post',{text:'hello',confirm:true})).delivered,true);await p.enqueue('room1',{type:'board.updated'});await p.pump();const expected='sha256='+createHmac('sha256',p.config.webhook.secret).update(hookHeaders['x-orivane-timestamp']+'.'+hookBody).digest('hex');assert.equal(hookHeaders['x-orivane-signature'],expected);const keys=await f.app.store.keys('hook:');assert.equal((await f.app.store.get(keys[0])).state,'delivered');await p.pump();assert.equal(remote.requests.filter(r=>r.url==='/hook').length,1);}finally{await f.close();await remote.close();}});
test('Provider network rejects private addresses and redirects unless local services are explicitly configured',async()=>{for(const ip of ['127.0.0.1','10.0.0.3','172.16.4.5','192.168.2.1','169.254.169.254','::1','::ffff:127.0.0.1','::ffff:7f00:1','fd00::1'])assert.equal(privateAddress(ip),true,ip);assert.equal(privateAddress('8.8.8.8'),false);await assert.rejects(()=>requestExternal('http://127.0.0.1:9'),/HTTPS/);const remote=await mock((req,res)=>{res.writeHead(302,{Location:'http://169.254.169.254/latest'});res.end();});try{await assert.rejects(()=>requestExternal(remote.base,{allowPrivate:true}),/redirect/);}finally{await remote.close();}});
test('HTTP provider routes require an account in addition to room edit permission',async()=>{const f=await fixture();try{const room=await f.room();assert.equal((await f.request('/api/rooms/'+room.id+'/ai',{task:'summarize',items:[],consent:true},{},'POST',f.headers(room))).status,401);const auth=await f.register();const response=await f.request('/api/rooms/'+room.id+'/ai',{task:'summarize',items:[],consent:true},auth,'POST',f.headers(room));assert.equal(response.status,503);assert.match(await response.text(),/Configure/);}finally{await f.close();}});
