import test from 'node:test';
import assert from 'node:assert/strict';
import { fixture } from './helpers/fixture.js';
import { BoardDocument, validateProps } from '../public/core/model.js';
import { appendAudit, verifyAudit } from '../server/identity.js';
test('Named server versions restore rich text, geometry and removed objects with new stamps',async()=>{const f=await fixture();try{const r=await f.room(),h=f.headers(r),d=new BoardDocument('tester');d.merge(f.doc.snapshot());const post=(a,b)=>f.request('/api/rooms/'+r.id+'/'+a,b,{},'POST',h);let op=d.transact([{id:'note',props:{text:'Before',richText:[{text:'Before',marks:{bold:true}}]}}]);assert.equal((await post('ops',op)).status,200);const version=await (await post('versions',{name:'Golden'})).json();op=d.transact([{id:'note',props:{text:'After',richText:[{text:'After',marks:{italic:true}}],x:500}},{id:'extra',props:{type:'rect',text:'Later'}}]);assert.equal((await post('ops',op)).status,200);assert.equal((await post('restore',{version:version.id})).status,200);const current=new BoardDocument('read');current.merge(await(await f.request('/api/rooms/'+r.id+'/snapshot',undefined,{},'GET',h)).json());assert.equal(current.get('note').x,0);assert.deepEqual(current.get('note').richText,[{text:'Before',marks:{bold:true}}]);assert.equal(current.get('extra'),null);assert.ok(current.clock>d.clock);const audit=await(await f.request('/api/rooms/'+r.id+'/audit',undefined,{},'GET',h)).json();assert.equal(audit.valid,true);assert.ok(audit.events.some(x=>x.action==='version.restored'));assert.equal((await post('delete',{confirm:true})).status,200);assert.equal(await f.app.store.get(`version:${r.id}:${version.id}`),null);assert.equal((await f.request('/api/rooms/'+r.id+'/snapshot',undefined,{},'GET',h)).status,404);}finally{await f.close();}});
test('Invalid scalar text, geometry and boolean payloads cannot poison durable snapshots',()=>{for(const props of [{text:100},{bold:'true'},{opacity:4},{rows:0},{cols:31},{rotation:'0'},{external:{x:1}}])assert.throws(()=>validateProps(props));});
test('Audit retention keeps a verifiable prefix anchor while trimming expired metadata',()=>{const target={retentionDays:7};const first=appendAudit(target,'user','old');first.at=Date.now()-8*86400000;const {hash,...data}=first; // Rebuild the historical fixture hash before trimming.
// Expired records are removed, and the retained chain is anchored to the last removed hash.
appendAudit(target,'user','new');assert.equal(target.audit.length,1);assert.equal(target.auditAnchor,hash);assert.equal(verifyAudit(target.audit,target.auditAnchor),true);});
test('Accepting a lesser invitation cannot demote the last workspace owner',async()=>{const f=await fixture();try{const a=await f.register(),ws=await(await f.request('/api/workspaces',{name:'Keep ownership'},a)).json(),invite=await(await f.request(`/api/workspaces/${ws.id}/invites`,{role:'viewer'},a)).json();assert.equal((await f.request('/api/workspace-invites/accept',{token:invite.token},a)).status,200);const result=await(await f.request(`/api/workspaces/${ws.id}`,undefined,a)).json();assert.equal(result.role,'owner');}finally{await f.close();}});
